package key

const (
	COOKIE_NAME = "session"

	COOKIE_VALUE_KEY_USERNAME = "username"

	PATH_VALUE_USERNAME_KEY  = "username"
	PATH_VALUE_DEVICE_ID_KEY = "deviceid"

	CONTEXT_VALUE_CURRENT_USERNAME_KEY = "CURRENT_USER"
	CONTEXT_VALUE_CURRENT_DEVICE_KEY   = "CURRENT_DEVICE"
	CONTEXT_VALUE_REQUEST_KEY          = "REQUEST"
)
